ietf-tools/purple

rpc/api.py
This works against current `feat/rpc-api` on the datatracker.
One wrinkle comes from the OpenAPI requirement that `object` keys be strings - see line 34 of `rpc/api.py`. We might consider changing the datatracker's API to return an array of objects, then converting that to the map we want after retrieving it. [This datatracker PR](https://github.com/ietf-tools/datatracker/pull/6392) implements that and I'll create an alternative PR here to match that change.
As noted on #12, only one of this or that should be merged, so I'm marking this as a draft.
=> feat: Use bulk lookup of Person name

client/components/LabelPicker.vue, client/pages/docs/[id].vue, rpc/api.py, rpc/factories.py, rpc/management/commands/create_rpc_demo.py, rpc/serializers.py, rpctracker/urls.py
This adds a (very) rough document page at `/docs/<draftname>` that contains a (working!) widget to manage its labels.
=> feat: Manage labels on an RfcToBe

client/components/LabelEditDialog.vue, client/components/LabelPicker.vue, client/pages/docs/[id].vue, rpc/api.py, rpc/serializers.py
Also use ModelViewSet for LabelViewSet for brevity
=> refactor: Fix leftover uses of slug as id

client/components/Badge.vue, client/components/DocumentTable.vue, client/components/Label.vue, client/components/LabelPicker.vue, client/pages/docs/[id].vue, client/pages/labels/index.vue, client/pages/queue/[section].vue
Adds a `<Label>` component to simplify consistent rendering of labels. Adds an icon to `is_exception` labels.
=> feat: <Label> component

client/components/DocumentCard.vue, client/pages/docs/assignments.vue, rpc/api.py, rpctracker/urls.py
Randomly assigns docs as needing assignment and allows filtering of documents on the assignments page
=> feat: Filter docs needing assignment

client/pages/docs/[id].vue, rpc/api.py
Fills in the doc page with the data we have in the model. Improves the formatting for the document info and status summary cards.
=> feat: Real doc info / deadline

rpc/management/commands/purge.py
=> fix: stricter purge confirmation

client/pages/queue/[section].vue
The Assignee column now looks like this...
Is that the intended formatting? Does this need tests?
=> feat: Assignee people

rpc/dt_v1_api_utils.py, rpc/models.py
I thought about  refactoring the managers to use something generic, but want to move ahead for now without that. If we get a third I'll do that refactor.
=> feat: align with datatracker StreamName

client/app.vue, client/components/Badge.vue, client/components/Button.vue, client/components/DocumentCard.vue, client/components/DocumentCards.vue, client/components/DocumentTable.vue, client/components/HeaderNav.vue, client/components/OverlayModal.vue, client/components/RefreshButton.vue, client/components/RfcToBeCreateDialog.vue, client/components/RpcLabelEditDialog.vue, client/components/RpcLabelPicker.vue, client/components/UserCreateDialog.vue, client/eslint.config.mjs, client/nuxt.config.ts, client/package-lock.json, client/package.json, client/pages/auth48/[section].vue, client/pages/clusters/[number].vue, client/pages/clusters/index.vue, client/pages/docs/[id].vue, client/pages/docs/assignments.vue, client/pages/docs/import.vue, client/pages/docs/index.vue, client/pages/index.vue, client/pages/labels/index.vue, client/pages/queue/[section].vue, client/pages/stats.vue, client/pages/team/[id].vue, client/pages/team/index.vue
This builds on #202 and eliminates the vue lint that cropped up. The new stuff here is just the last two commits.
There are still some bugs / type errors, but this makes eslint happy.
=> refactor: delint JS

client/app.vue, client/assets/css/tailwind.css, client/components/HeaderNav.vue, client/layouts/default.vue, client/nuxt.config.ts, client/pages/login.vue, client/stores/user.ts, client/utilities/head.ts, client/utilities/url.ts
* Adds a `/login/` route asking the user to login. Hide all UI until authorised.
=> feat: Login route

purple/settings/base.py
These are unnecessary since datatracker handles account management.
=> chore: Remove password validation rules

client/package-lock.json, client/package.json
Reka wasn't added to package.json
=> chore: add Reka UI

rpc/factories.py, rpc/tests_factories.py, rpcauth/tests.py
these changes make all tests pass
```dev ➜ /workspace $ ./manage.py test 
Found 9 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........
----------------------------------------------------------------------
Ran 9 tests in 0.247s
OK
Destroying test database for alias 'default'...```
=> test: fix current tests

.github/workflows/test.yml, datatracker/migrations/0001_initial.py, datatracker/migrations/0002_initial.py, datatracker/migrations/0003_document_intended_std_level.py, dev/build/gunicorn.conf.py, errata/migrations/0001_initial.py, errata/migrations/0002_populate_status.py, errata/migrations/0003_populate_type.py, manage.py, purple/settings/production.py, purple/tests.py, pyproject.toml, rpc/management/commands/create_rpc_demo.py, rpc/migrations/0001_initial.py, rpc/migrations/0005_rpcperson_is_active.py, rpc/serializers.py, rpcauth/migrations/0001_initial.py, rpcauth/migrations/0002_user_avatar_user_name_and_more.py, rpcauth/tests.py, utils/jsonlogger.py
- setting minimal configuration for ruff (line-length = 88)
- reformat code to make it ruff compliant
- add ruff format validation in workflow tests
=> chore: ruff formatting and adding ruff to workflow tests

client/components/DocumentCard.vue, client/pages/docs/assignments.vue, client/utilities/typescript.ts
* migrate it to Reka UI w/ design fixes for dark mode
* fix assignment removal (needs trailing slash)
=> fix: Assignments bug fixes, and Reka UI

README.md
* VSCode's local port host: allInterfaces
=> docs: VSCode's local port host: allInterfaces

client/pages/docs/[id]/enqueue.vue
There was a `TODO` to save labels which this PR does
=> feat: Save labels

rpc/api.py, rpc/serializers.py
make "person_id" optional field for create of authors
=> feat: create author without dt person

client/components/AssignmentState.vue, rpc/management/commands/create_rpc_demo.py, rpc/migrations/0011_alter_assignment_state.py, rpc/models.py
Better ergonomics, "in progress" -> "in_progress", adds "withdrawn" state.
=> refactor: Assignment state choices enum

dev/build/migration-start.sh, docker/scripts/app-init.sh
For models with simple history, this will create initial history entries for existing rows with a "now" timestamp. Models that already have history will be ignored.
This fixes an issue where labels created by the `NNNN_populate_labels.py` migration do not show up in rfc-to-be change histories.
=> fix: initial history for existing data

client/pages/queue/[section].vue, rpc/lifecycle.py
todo: need eventually to apply different colors to roles and activities in future PR
=> feat: show pending activities in queue page

client/pages/queue/[section].vue
remove duplicate column deadline
This commit removes the 2nd one
=> fix: remove duplicate columns and simplify logic

client/app/components/Anchor.vue, client/app/layouts/default.vue, client/app/pages/auth.vue, client/app/utils/url.ts
* Login link was broken due to several bugs
*  `&` rather than `&&` in `Anchor.vue`
* a bad regex for detecting `/oidc/` links
* Login page formatting wasn't full screen
=> fix: login

rpc/management/commands/purge.py
fix issues of DB relations preventing running purge script
=> fix: add missing models for purge command

client/app/components/DocumentCard.vue, client/app/utils/url.ts
* Adding links to documents from `/docs/assignments`
=> feat: Assignment links

client/app/components/DocInfoCard.vue, client/app/pages/docs/import.vue, datatracker/models.py, rpc/serializers.py
receive consensus value from DT and display it for import detail and queue detail page
use caching in memcache
=> feat: show consensus on draft info pages

client/app/pages/queue/queue.vue, rpc/serializers.py
addresses some improvements from https://github.com/ietf-tools/purple/issues/507
- show RFC number and pages on queue page (`Pages` was previously mis-titled as `Status`)
- enable search for draft title and rfc number
=> feat: batch #1 UI improvements queue

client/app/components/RpcTextarea.vue
=> fix: restore previously reverted change of icon

client/app/components/AssignmentModal.vue, client/app/components/BaseBadge.vue, client/app/components/BaseButton.vue, client/app/components/RpcRowMessage.vue, client/app/components/RpcTextarea.vue, client/app/components/WorkloadSummary.vue, client/app/pages/queue/queue.vue, client/app/utils/promise.ts, client/app/utils/queue.ts, client/app/utils/snackbar.ts, client/app/utils/typescript.ts, client/package-lock.json, client/package.json
* From the route `/queue/queue` adds a modal to make role assignments / changes.
**screenshots**
=> feat: assignments modal

client/app/pages/queue/queue.vue
* restore search on `/queue/queue/`
=> fix: restore search
