ietf-tools/purple

rpcauth/backends.py, rpcauth/tests.py, rpctracker/settings.py
This makes up for some shortcomings of mozilla-django-oidc's validation
=> fix: Add claim/token validation to OIDC backend

.gitignore, datatracker/models.py, datatracker/rpcapi.py, docker/scripts/app-init.sh, openapi/config.yaml, openapitools.json, rpc/api.py, rpc/management/commands/create_rpc_demo.py, update-rpcapi
Mostly just gets a few things out of the `datatracker.models` file where they'd been stashed for convenience.
@NGPixel- could you check in particular the 3rd commit, which puts all the config for the code generator call into one file (the previously ignored `openapitools.json` file). It seems to work for me both with vscode and the old-fashioned way but I'm not familiar enough with vscode to be sure I didn't break it.
=> refactor: Rationalize the API usage a bit

rpc/api.py, rpctracker/settings.py
Uses session-based authentication and requires authentication before permission is granted to access API endpoints.
Will apply to any views decorated with `@api_view` or any class-based `APIView` views (if we go that route later).
=> feat: Require auth to access backend api

client/components/LabelEditDialog.vue, client/pages/docs/[id].vue, client/pages/labels/index.vue, rpc/api.py, rpctracker/urls.py
This replaces the label management API with a DRF ViewSet implementation and adds the necessary URL routing plumbing.
=> refactor: Use DRF viewset for label API

client/components/HeaderNav.vue, client/components/SidebarNav.vue, client/pages/docs/index.vue, client/stores/user.js, datatracker/models.py, rpc/api.py, rpc/management/commands/create_rpc_demo.py, rpcauth/models.py, rpctracker/urls.py
This is a bunch of pieces aimed at showing the current user's documents on the Documents tab, renamed to My Documents.
To do this, passes the RpcPerson ID for the current user to the front end as part of the profile. This is used to filter the full list of assignments down to those assigned to the current user. I suspect we'll eventually want to add API endpoints so we can do this without giving non-manager people access to the full assignment data, but that's for another day.
Additionally passes an `isManager` flag that is use to show (or not) the "Manage Assignments" button on the "My Document" page. This can also be used to show/hide other UI elements ("Manage Clusters", etc?), but I haven't done that yet.
To make this easier to demo, I've added the ability to "pretendToBe" a different …
=> feat: My Documents + other bits

client/components/SidebarNav.vue, client/pages/index.vue, client/pages/team/index.vue
Among the changes, hides the "Add team member" button. Not sure if we want to entirely hide the "Team" page or not. It's currently titled "Manage Team Members," but maybe editors should get a "View Team Members"?
=> feat: Hide mgmt items from non-managers

client/components/DocumentTable.vue
Adds a placeholder icon to each column so that each column has the same width regardless of whether it's sorted.
fixes #49
question: does this need tests? I'm guessing not.
We should probably consider changing the `<a>`s to be `<button>`s and use [`aria-sort`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort) for a11y reasons.
=> fix: DocumentTable sort column width wobble.

client/components/HeaderNav.vue, client/components/RpcLabelPicker.vue, client/components/TitleBlock.vue, client/pages/docs/[id].vue, client/pages/labels/index.vue, client/pages/stats.vue
Fixes #81 (in the sense that it fixes some current components/pages but I may have missed some)
Mostly this adds some Tailwind `dark:*` CSS classes, and—where possible—moves inline classes up to a container class to avoid repetition.
=> fix: dark mode

client/components/DocumentCard.vue
Noticed a few places where we still had snake case names in JS code. The API generator converts these.
=> fix: camelCase several API names

client/package-lock.json, client/package.json, docker/base.Dockerfile
Node.js v22 becomes the LTS version in October 2024
=> chore(deps): Node.js v22

client/eslint.config.mjs, client/nuxt.config.ts, client/package-lock.json, client/package.json
Gets rid of jquery settings and eliminates need for the `FlatCompat` helper.
Please check whether the ordering of rules is correct.
This leads to about 30 errors and 150 warnings in `*.vue` files - I think they're legitimate bugs, but not cleaning up until we agree that this is a correct eslint config.
=> chore: clean up eslint.config.mjs

client/components/DocumentTable.vue, client/components/DocumentTableTypes.ts, client/pages/queue/[section].vue
Fixes #209 
This creates a problem because the `labels` field is a `Label` object and `<DocumentTable>` can't deal with it.
It was added as part of the typescript conversion and I'm not certain why, but I don't think it's needed functionally.
=> fix: remove field from labels col

rpc/management/commands/purge.py
Four additional tables to purge when the `purge` command runs:
| model                          | table                        |
|--------------------------------|------------------------------|
| `HistoricalRfcToBeLabel` \[1\] | `rpc_historicalrfctobelabel` |
| `HistoricalRfcToBe` \[1\]      | `rpc_historicalrfctobe`      |
| `HistoricalLabel` \[1\]        | `rpc_historicallabel`        |
| `RpcDocumentComment`           | `rpc_rpcdocumentcomment`     |
1.  managed by `django-simple-history`
=> chore: purge more tables

k8s/datatracker-settings_local.py, k8s/datatracker.yaml, k8s/kustomization.yaml
This drops the datatracker's NFS mount at `/a` and instead sets up just enough of a filesystem to pass the startup checks.
=> ci: datatracker StatefulSet

datatracker/rpcapi.py, rpcauth/backends.py, rpctracker/settings/production.py
This adds cloudflare service token headers to OIDC back channel requests to the OP (I.e., datatracker) and to datatracker API calls. Tries to be paranoid about leaking the tokens on requests to other hosts. For staging, the `PURPLE_SERVICE_TOKEN_HOSTS` will contain only the hostname for the staging datatracker-rpc instance.
=> feat: CF service tokens

client/nuxt.config.ts
Avoids a round of optimize/reload on the first run and fixes an issue where vue3-snackbar is optimized but not reloaded, requiring manual restart of the dev server to work around.
=> ci: declare vite deps

purple/urls.py, rpc/api.py, rpc/management/commands/add_dumpinfo.py, rpc/serializers.py, rpc/utils.py
This adds a management command to create a `DumpInfo` with a timestamp and adds a stub of a version API at `/api/rpc/version/`. That does not currently provide useful version info, but includes the dump timestamp when it's available.
=> feat: version/dumpinfo mgmt and api

.gitignore, datatracker/admin.py, purple/settings/base.py, rpc/admin.py, rpcauth/backends.py
what was done:
- on login to purple, grant Admin permission if DT user's role tuple ["leadmaintainer", "tools"] is set
still to do:
- build static files for dev and prod (run `./manage.py collectstatic`) - needs currently to be done manually
- discuss proper permissions to a) access purple, b) access Django admin
=> feat: enable django admin, add models to admin

rpc/api.py
This restricts access to authenticated users.
Default setting is[^1]:
```
"DEFAULT_PERMISSION_CLASSES": [
"rest_framework.permissions.IsAuthenticated",
],
```
PR #274 seems to address the UI part of this.
[^1]: https://github.com/ietf-tools/purple/blob/main/purple/settings/base.py#L89-L91
=> fix: Allow API access only to authenticated users

purple/settings/__init__.py, purple/settings/base.py, purple/settings/development.py, purple/settings/production.py, rpcauth/utils.py, rpcauth/views.py
Configures mozilla-django-oidc to end the session with the OIDC provider (OP) after ending the local session. Until front end support is added, this can be exercised manually by visiting `/oidc/logout/`.
The OP is instructed to redirect to purple's root path after ending the OP session. In order for this to work, the OIDC client in the datatracker needs to be edited to add this to the `post_logout_redirect_uris` list. This can be done from the admin for dev until we update the database image action. We'll need to do it manually for production.
=> feat: RP-initiated logout from OIDC provider

.gitignore, client/pages/docs/index.vue, rpc/admin.py, rpc/api.py, rpc/serializers.py, rpcauth/admin.py
Backend: 
new behavior: 
- only assignments of currently authenticated user are returned for endpoints `GET /api/rpc/assignments` 
- assignments in payload also contain embedded data of related RfcToBe
Frontend:
Improve API calls on page "My Documents (Documents assigned to me)", requesting all documents and all assignments and intersecting is no longer required
=> refactor: improve fetching my documents

rpc/models.py, rpc/serializers.py
I think this is a cleaner approach than #323, but does essentially the same thing
=> feat: queryset-based active filters for assignments/actionholders

rpcauth/backends.py
The existing name, `dt-person-...` is inaccurate because the suffix is a subject_id, not a datatracker Person PK.
=> fix: more accurate username

purple/urls.py, rpc/admin.py, rpc/api.py, rpc/migrations/0014_rfcauthor_unique_author_per_document.py, rpc/models.py, rpc/serializers.py
1) added endpoints:
List all authors of doc:
GET /documents/<draft_name>/authors/
Create author:
POST /documents/<draft_name>/authors/
Retrieve author:
GET /documents/<draft_name>/authors/<author_id>/
Update author:
PUT /documents/<draft_name>/authors/<author_id>/
Partial update author:
PATCH /documents/<draft_name>/authors/<author_id>/
Delete author:
DELETE /documents/<draft_name>/authors/<author_id>/
2) added constraint for unique DT-Person per Doc in RfcAuthor
=> feat: add endpoints to list/retrieve/update/destroy RfcAuthors

rpc/migrations/0015_alter_rpcperson_can_hold_role_and_more.py, rpc/models.py
Allows RpcPerson to be created/managed in the admin. Does not affect the database schema.
=> fix: blank=True for several RpcPerson fields

.github/workflows/build.yml, dev/build/backend.Dockerfile, dev/build/statics.Dockerfile, k8s/nginx-purple.conf, k8s/purple.yaml
Builds and deploys a statics server so the admin pages will work in staging. (Likely a temporary arrangement until we build out external statics handling/serving.)
=> chore: deploy statics for k8s staging

datatracker/models.py, purple/urls.py, rpc/api.py, rpc/serializers.py
Adds a `search_datatrackerpersons` API call. This makes an upstream call to a new datatracker rpcapi endpoint that performs a `Person` search.
There's some complexity around making this work with DRF's gearing, particularly for pagination and schema generation. If this has crossed the threshold into "too much magic" it would be possible to consider a more explicit implementation, but there'll be a fair bit of repetitive code / explicit schema annotation.
=> feat: search_datatrackerpersons API

client/pages/docs/import.vue
Do we have any way to reverse paths so we're not hardcoding them into .vue files?
This stays with the current convention of not using trailing slashes.
=> fix: navigate to enqueuing page after initial ingest

client/components/DocLabelsCard.vue, client/pages/docs/[id]/enqueue.vue, client/utilities/sort.ts
* Group the two columns of labels under a 'Complexities' heading,
This doesn't yet change the layout of the 3rd column of labels. That can happen in a later PR.
* the groups of labels (grouped by ":" prefixes) weren't ordered so the initial ungrouped list could appear in the middle of other groups, but now they're sorted so they'll always appear first.
=> feat: complexities heading group, sorting labels

rpc/api.py, rpc/serializers.py
also:
- add schema-extensions to fix ERRORs for version/profile viewsets
- use reusable function _extend_schema_with_draft_name_ to DRY
=> feat: add CRUD endpoints for doc-references

rpc/migrations/0017_blankable_rpcrelateddocument_targets.py, rpc/models.py, rpc/serializers.py, rpc/utils.py
Refactors part of the references API to make it partially usable by the front end. Fixes
* `documentsReferencesList()`
* `documentsReferencesRetrieve()`
but breaks (temporarily!)
* `documentsReferencesCreate()`
* `documentsReferencesUpdate()`
* `documentsReferencesPartialUpdate()`
Instead of serializing the models exactly, this sorts out which of `target_document` and `target_rfctobe` is set and serializes the name of that draft as `targetDraftName`. Drops fields that are redundant (mainly source, which is redundant with the draftName in the path parameter; also does not indicate whether the `targetDraftName` is an RfcToBe or Document - we may need to add that later, but it's currently redundant with the relationship type)
Also adds `blank=True` to the target fields in the model. This …
=> fix: use draftNames in references API + admin fix

client/components/EditAuthorsAdd.vue
* RekaUI's Combobox does additional clientside filtering on the results which we want to disable via ` :ignore-filter="true"`
fixes #400
=> fix: author search filter disable

purple/settings/base.py
The `BASE_PATH` computed in `settings/base.py` was meant to point at the project root. It seems not to have been updated correctly when we split `settings.py` into a module, and was instead pointing at the `purple` directory one level in. This came up because the Django templates were no longer working. It was looking in `purple/templates/` instead of just `templates/`.
=> chore: fix settings BASE_PATH

purple/urls.py, rpc/api.py, rpc/serializers.py
Adds `DocRelationshipNamesList` and `DocRelationshipNamesRetrieve` API calls. Small refactor to use a common `NameSerializer` for subclasses of `models.Name` instead of maintaining a fleet of serializers identical but for name and model name.
=> feat: DocRelationshipNames viewset

client/pages/docs/[id]/index.vue, client/utilities/snackbar.ts
* fixes javascript `const` ordering bug. Not sure why we don't see this on some environments but might be due to minification (ie, swapping `const` to `var` causing hoisting)
=> fix: doc bug

client/pages/docs/[id]/index.vue, rpc/serializers.py
* hide label picker
* make backend labels API include `used` and use that to filter labels in the frontend
=> feat: hide previous label picker, filter labels by used

client/components/LabelsFilter.vue, client/pages/queue/[section].vue, client/utilities/checkbox.ts
* allows filtering by labels in the response (in the screenshot note the 'Label filters' section above the table)
I'll change the tristate checkbox UI in a subsequent PR
**screenshot**
Intentionally, this UI is a simple toggle list (rather than a more complicated [table column filter popout UI](https://i.imgur.com/LgA1F2R.png)) just to keep it simple for now. There are more filters to be added in subsequent PRs. Once we know all the filters we might revise it the overall filter UI.
=> feat: queue filter by labels

client/components/AssignmentState.vue, client/pages/docs/[id]/index.vue, client/pages/queue/[section].vue
* on draft info page for Current Assignments show the assignment state with a badge
* on the queue tab ensure multiple Action Holders are visible, and use `body` if present rather than `name`
=> feat: Current assignments state and action holders

client/components/DocInfoCard.vue, client/components/ErrorAlert.vue, client/pages/docs/[id]/enqueue.vue, client/pages/docs/[id]/index.vue, client/pages/queue/[section].vue, client/pages/team/[id].vue, rpc/api.py, rpc/models.py, rpc/serializers.py
This reorganizes and adjusts the `RfcToBeSerializer` and `QueueItemSerializer` and related smaller serializers. Surrounding code is refactored to work with the changes. Highlights:
* Splits the history serialization out of `RfcToBeSerializer`
- adds `documentsHistoryList` API call to fetch only the history for a draft (n.b., the commit comment below calls it `...Retrieve`, but subsequent refactors changed it to `...List`)
- adjusts the document index page to refresh history after adding labels
* Eliminates all of the `SerializerMethodField` fields from these serializers in favor of cleaner options
* Adds missing fields that seem logical for the two serializers
- Added `actionholder_set` and `assignment_set` to `RfcToBeSerializer`
- Added a few easily computed fields likely to be wanted on …
=> refactor: clean up RfcToBe-related serializers

client/components/DocumentDependencies.vue, client/pages/docs/[id]/index.vue, rpc/api.py, rpc/migrations/0006_populate_doc_relationship_names.py
for each related doc, call API for additional info, filter out assignments and pending_activities and pass them to component
@holloway I didn't change the API-payload, but added additional API calls to fetch draft details. Let me know what you think of this approach
=> feat: show assignments and pend activities

client/components/RpcLabelEditDialog.vue, client/pages/labels/index.vue
Feature-wise, this exposes the "used" flag through the "manage labels" page. Cleans up some reactivity / state management / error displays to be more in line with how we've evolved. There's more cleanup to be done.
Adds a very simple red "X" mark on the label list display to indicate labels with used = False. This will need to be improved, but it's more than I have time for now.
=> feat: label management improvements

client/components/DocumentDependencies.vue, client/components/DocumentDependenciesAdd.vue, client/pages/docs/[id]/index.vue
refactor: move logic to call APIs for related docs/assignments/pending activities from the parent component to the DocumentDependancies.vue component
This makes the component work independently from where it is used
=> fix: refactor RelatedDocs widget to make it work in enqueue page

client/components/DocInfoCard.vue, client/components/DocumentDependencies.vue, client/pages/docs/[id]/enqueue.vue, client/pages/docs/[id]/index.vue
- show cluster number
- cluster number links to cluster info page
- make the related docs a link to their respective draft info page
=> feat: add cluster info

client/pages/queue/[section].vue
- Assignee (should allow multiple) should just be Assignees and the same change for Action Holders.
- Exception Column is unnecessary - we have Exception labels and the triangle-bang will show on them.
- in the Cluster column, we shouldn't show the icon unless the doc is actually in a cluster
=> feat: change some columns on queue page
